export class Device{
CardFormat:string;
Debug:number;
Door:any | null;
IO:number;
IOad:string;
Id:number;
LastEventTime:string;
Ping:number;
PingCheck:number;
SonGecen:any|null;
SourceName:string;
TemplateCount:number;
TimeSend:number;
UserCount:number;
controllerno:number;
deviceImage:any | null;
durum:string;
firma:any|null;
firmaad:any|null;
ip:string;
kind:number;
kindad:string;
latitude:any|null;
lokasyon:string;
longtitude:any|null;
model:number;
modelad:string;
name:string;
networkdurum:string;
port:number;
templatecapacity:number;
usercapacity:number;
}
